name: Reportar un error
description: Informar de un error.
title: "[bug]: Título del error y donde se encuentra"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Antes de realizar un reporte recuerde lo siguiente:
        - **Un buen título** debe contener el problema y la localización, por ejemplo: `Color incorrecto en la portada principal`.
        - Debe ser lo más **descriptivo posible**, si el problema no se puede reproducir será marcado como inválido.
        - **Verifique la integridad de su conexión**: El uso de una red VPN o red insegura **puede provocar cambios inesperados en el contenido del sitio WEB**, ya sea debido a problemas de servicios de caché intermedios, certificados SSL mal configurados o ataques de tipo [MITM](https://cwe.mitre.org/data/definitions/300.html).

        Complete los siguientes campos:
  - type: textarea
    id: what-happened
    attributes:
      label: ¿Cual es el problema?
      description: Indique con detalle cual es el problema, si es necesario indique como se puede reprducir. Si no podemos reproducir el problema será marcado como inválido.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Propuesta de solución
      description: ¿Qué propone para remediar este problema? (opcional).
    validations:
      required: false
  - type: textarea
    id: localization
    attributes:
      label: Localización del problema
      description: Indique en que lugares se presenta el problema, etso nos permitirá saber donde realizar las correcciones.
    validations:
      required: true
  - type: textarea
    id: enviroment
    attributes:
      label: Entorno
      description: Indique qué tecnología está utilizando para observar el problema, por ejemplo, el nombre y versión del navegador WEB, Sistema Operativo y similares.
      value: |
        - Nombre y versión del navegador WEB:
        - Nombre y versión (o distribución) del Sistema Operativo:
        - ¿Estoy utilizando VPN o una red insegura?:
    validations:
      required: true
