name: Deploy
version: 0.1

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Code checkout
      uses: actions/checkout@v3

    - name: NodeJS setting
      uses: actions/setup-node@v3

    - name: SSH setting
      run: |
        mkdir -p ~/.ssh;
        printenv;
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa;
        chmod 600 ~/.ssh/id_rsa;
        ssh-keyscan deploy.insidesecurity.cl > ~/.ssh/known_hosts;

    - name: Install project dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy
      run: |
        rsync -tvrz --delete ./build/ insidesecurity.cl@deploy.insidesecurity.cl:/home/insidesecurity.cl/public_html/;
